name: os_search
channels:
  - conda-forge
dependencies:
  - r-base=4.4
  - r-shiny
  - r-bslib
  - r-dt
  - r-shinybusy
  - r-dplyr
  - r-stringr
  - r-purrr
  - r-tibble
  - r-readxl
  - r-readr
  - r-httr2
  - r-jsonlite
  - r-httpuv
  - python=3.12
  - pip
  - numpy
